// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAowryOVZLdC9zODErw9b_ffCWlZSnBnl8',
    appId: '1:693811932076:web:13a6d3717bd627ec5c6809',
    messagingSenderId: '693811932076',
    projectId: 'auralight1',
    authDomain: 'auralight1.firebaseapp.com',
    storageBucket: 'auralight1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv582-J96suy9FBh4k18gd_4AZmiEfhQQ',
    appId: '1:693811932076:android:a94b4832c80557855c6809',
    messagingSenderId: '693811932076',
    projectId: 'auralight1',
    storageBucket: 'auralight1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvZh1kq3uKNdSpJa15AiBn3Rz5HeQRdiA',
    appId: '1:693811932076:ios:db8319bbda78d4665c6809',
    messagingSenderId: '693811932076',
    projectId: 'auralight1',
    storageBucket: 'auralight1.firebasestorage.app',
    iosBundleId: 'com.example.auralight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvZh1kq3uKNdSpJa15AiBn3Rz5HeQRdiA',
    appId: '1:693811932076:ios:db8319bbda78d4665c6809',
    messagingSenderId: '693811932076',
    projectId: 'auralight1',
    storageBucket: 'auralight1.firebasestorage.app',
    iosBundleId: 'com.example.auralight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAowryOVZLdC9zODErw9b_ffCWlZSnBnl8',
    appId: '1:693811932076:web:501ad7c1dc8a5cfd5c6809',
    messagingSenderId: '693811932076',
    projectId: 'auralight1',
    authDomain: 'auralight1.firebaseapp.com',
    storageBucket: 'auralight1.firebasestorage.app',
  );
}
